---
# MD013/line-length
MD013:
  line_length: 260

# MD026/no-trailing-punctuation
MD026: false

# MD033/no-inline-html
MD033: false

# MD041/first-line-heading/first-line-h1
MD041: false

# MD060/table-column-style Table column style
MD060: false
