---
# MD013/line-length
MD013: false

# MD026/no-trailing-punctuation
MD026: false

# MD033/no-inline-html
MD033: false

# MD034/no-bare-urls
MD034: false

# MD041/first-line-heading/first-line-h1
MD041: false

# MD060/table-column-style Table column style
MD060: false
